SELECTED_FEATURES_28 = [
    "IAT",
    "Protocol Type",
    "ICMP",
    "Magnitue",
    "Variance",
    "syn_flag_number",
    "syn_count",
    "AVG",
    "UDP",
    "Tot size",
    "psh_flag_number",
    "Min",
    "Tot sum",
    "Header_Length",
    "TCP",
    "fin_flag_number",
    "ack_flag_number",
    "flow_duration",
    "Max",
    "HTTP",
    "Weight",
    "rst_flag_number",
    "Std",
    "Number",
    "Radius",
    "ack_count",
    "fin_count",
    "Duration",
]